# Generated by Django 3.2 on 2024-04-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, verbose_name='Слово')),
                ('tf', models.IntegerField(verbose_name='Количество вхождений')),
                ('idf', models.FloatField(verbose_name='Частота вхождений в тексты')),
            ],
            options={
                'verbose_name': 'слово',
                'verbose_name_plural': 'Слова',
                'ordering': ('-idf',),
            },
        ),
    ]
