# Generated by Django 3.2 on 2024-04-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='file_token',
            field=models.CharField(default=123, max_length=255, verbose_name='Токен файла'),
            preserve_default=False,
        ),
    ]
